// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3EfGVNLCa_ih8WHcl8ywqeKJmu-4ryXE',
    appId: '1:862069120204:web:d5e1a5f2df752b0cb9b669',
    messagingSenderId: '862069120204',
    projectId: 'rentall-5d0bd',
    authDomain: 'rentall-5d0bd.firebaseapp.com',
    storageBucket: 'rentall-5d0bd.firebasestorage.app',
    measurementId: 'G-4SYS2RNXXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPZc7GvDlOP9GuppMsQ72PDzHtPBnzUY',
    appId: '1:862069120204:android:b83fb94782a1f8ccb9b669',
    messagingSenderId: '862069120204',
    projectId: 'rentall-5d0bd',
    storageBucket: 'rentall-5d0bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhlzZuZDEhfHVmzXRHuskWByRTgcDacl4',
    appId: '1:862069120204:ios:1c3898ef55259810b9b669',
    messagingSenderId: '862069120204',
    projectId: 'rentall-5d0bd',
    storageBucket: 'rentall-5d0bd.firebasestorage.app',
    iosBundleId: 'com.example.rentall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhlzZuZDEhfHVmzXRHuskWByRTgcDacl4',
    appId: '1:862069120204:ios:1c3898ef55259810b9b669',
    messagingSenderId: '862069120204',
    projectId: 'rentall-5d0bd',
    storageBucket: 'rentall-5d0bd.firebasestorage.app',
    iosBundleId: 'com.example.rentall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3EfGVNLCa_ih8WHcl8ywqeKJmu-4ryXE',
    appId: '1:862069120204:web:0e1993191a50135eb9b669',
    messagingSenderId: '862069120204',
    projectId: 'rentall-5d0bd',
    authDomain: 'rentall-5d0bd.firebaseapp.com',
    storageBucket: 'rentall-5d0bd.firebasestorage.app',
    measurementId: 'G-1GS0FHE1T2',
  );

  static initializeApp({required FirebaseOptions options}) {}
}
